Update version (v4.3.0)
arkedge/c2a-core pull request #304
Opened 2024-02-05 00:24 UTC by meltingrabbit

## 概要
v4.3.0 のリリース

## 備考
バグ修正と一部変数確保のポリシー変更が含まれるため，早急にリリースしたい．そのために，この差分にて，バージョンをあげる．

2024-02-05 01:57 UTC, sksat commented on CHANGELOG.md
> +- [#302](https://github.com/arkedge/c2a-core/pull/302): static に確保している packet 系の変数のローカル変数化
301 はバグ修正のついでに結果的に breaking になってしまったやつで，302 は真に breaking change のためのやつなので Breaking change 欄に書きたい

2024-02-05 02:00 UTC, meltingrabbit commented on CHANGELOG.md
> +- [#302](https://github.com/arkedge/c2a-core/pull/302): static に確保している packet 系の変数のローカル変数化
OK

2024-02-05 02:01 UTC, meltingrabbit commented on CHANGELOG.md
> +- [#302](https://github.com/arkedge/c2a-core/pull/302): static に確保している packet 系の変数のローカル変数化
なおした

2024-02-05 02:04 UTC, sksat commented on CHANGELOG.md
> +- [#301](https://github.com/arkedge/c2a-core/pull/301): 要求されるスタックメモリの容量が増加しており，[Requirements](./docs/general/requirements.md) を参考に，スタックメモリの容量を確認する（MUST）
ここで経緯として参照するとしたら #301 ではなく #303 でしょう（#301 に直接リンクしてもノイズになるだけ）

2024-02-05 02:05 UTC, meltingrabbit commented on CHANGELOG.md
> +- [#301](https://github.com/arkedge/c2a-core/pull/301): 要求されるスタックメモリの容量が増加しており，[Requirements](./docs/general/requirements.md) を参考に，スタックメモリの容量を確認する（MUST）
経緯，303参照してないですか？（L.23にある）

2024-02-05 02:06 UTC, meltingrabbit commented on CHANGELOG.md
> +- [#301](https://github.com/arkedge/c2a-core/pull/301): 要求されるスタックメモリの容量が増加しており，[Requirements](./docs/general/requirements.md) を参考に，スタックメモリの容量を確認する（MUST）
スタックメモリの要求がかわったPRは301で，経緯が303になるような書き方してるつもりです．

2024-02-05 02:07 UTC, sksat commented on CHANGELOG.md
> +- [#301](https://github.com/arkedge/c2a-core/pull/301): 要求されるスタックメモリの容量が増加しており，[Requirements](./docs/general/requirements.md) を参考に，スタックメモリの容量を確認する（MUST）
この書き方では全部読んだ上でちょっと意図を考えないと何言ってるかわからん（意図の把握の手戻りが大きい）ということです．suggest します．

2024-02-05 02:16 UTC, sksat requested changes

2024-02-05 02:16 UTC, sksat commented on CHANGELOG.md
> +  - 経緯は [#303](https://github.com/arkedge/c2a-core/issues/303) を参照
```suggestion
- [Requirements](./docs/general/requirements.md) を参考に，マイコンのスタックメモリの容量に余裕があるかどうか確認すること（MUST）
  - 今後ハードウェアに対する要求事項は [docs/general/requirements.md](docs/general/requirements.md) に書かれることになるので，今後のアップデートでも適宜確認すること
  - 今回の経緯は [#303](https://github.com/arkedge/c2a-core/issues/303) を参照
  - [#301](https://github.com/arkedge/c2a-core/pull/301) で要求されるスタック容量が増加している
  - [#302](https://github.com/arkedge/c2a-core/pull/302) で結果的に同程度以上のメモリ使用量削減を行っているため，実用上は今回のアップデートに伴って C2A user 側でメモリ使用量削減をする必要は無い
```

2024-02-05 02:26 UTC, meltingrabbit commented on CHANGELOG.md
> +- [#301](https://github.com/arkedge/c2a-core/pull/301): 要求されるスタックメモリの容量が増加しており，[Requirements](./docs/general/requirements.md) を参考に，スタックメモリの容量を確認する（MUST）
suggest 取り込みました @sksat

2024-02-06 01:04 UTC, sksat commented on CHANGELOG.md
> +## v4.3.0 (2024-02-05)
```suggestion
## v4.3.0 (2024-02-06)
```

2024-02-06 01:10 UTC, sksat approved these changes

2024-02-06 01:33 UTC, meltingrabbit commented
リリース日の修正ありがとう

2024-02-06 01:33 UTC, merged