WIP: C2A User 開発者のためのビルドオプションの簡易なドキュメントを追加
arkedge/c2a-core pull request #328
Opened 2024-03-29 04:42 UTC by meltingrabbit

## 概要
ひとことで

## Issue
- 関連する issue

## 詳細
詳しく

## 検証結果
test へのリンクや，検証結果へのリンク

## 影響範囲
XX系の動作がガラッと変わる，とか．

## 補足
何かあれば

2024-04-08 05:06 UTC, sksat requested changes

2024-04-08 05:06 UTC, sksat commented on docs/general/architecture.md
> +https://github.com/arkedge/c2a-core/blob/4472ef1a5670c2674f10b6b72b088d616367bd86/CMakeLists.txt#L24
デフォルトは Sub OBC 向けの実装となっており、MOBC を開発する時は MOBC FEATURE オプションを有効化する、という書き方の方が自然。

2024-04-08 05:06 UTC, sksat commented on docs/general/architecture.md
> +https://github.com/arkedge/c2a-core/blob/4472ef1a5670c2674f10b6b72b088d616367bd86/CMakeLists.txt#L24
> sub OBC 向けの実装となる

このドキュメントのスコープは c2a-core だけではなく C2A 全体のはずです。何が sub OBC 向けの実装になるんでしょうか。c2a-core が、ですよね。

2024-04-08 07:21 UTC, meltingrabbit commented
https://github.com/arkedge/c2a-core/pull/329 がマージされたので，rebase して追記します

2024-04-08 07:28 UTC, meltingrabbit commented on docs/application/overview.md
> +`ON` にすることで，全ての [c2a-core Application](/applications/) をビルドする．
修正しました

2024-04-08 07:29 UTC, meltingrabbit commented on docs/general/architecture.md
> +https://github.com/arkedge/c2a-core/blob/4472ef1a5670c2674f10b6b72b088d616367bd86/CMakeLists.txt#L24
修正しました（２個めの意図をくめてるかあまり自信がない）

2024-04-08 09:02 UTC, meltingrabbit commented
@sksat 
C2A_USE_SPACE_PACKET_AS_COMMON_PACKET
も追記しました，再度レビューお願いします．

2024-04-08 09:19 UTC, sksat commented on docs/application/overview.md
> +`ON` にすることで，test app 以外の全ての [c2a-core Application](/applications/) をビルドする．
上で書いてる
```suggestion
test app 以外の全ての [c2a-core Application](/applications/) をビルドする．  
```

2024-04-08 09:21 UTC, sksat commented on docs/core/ccsds.md
> +この実装をコンパイル対象に含める場合は，以下の `C2A_USE_CORE_CCSDS_AOS_SPACE_DATA_LINK_PROTOCOL`, `C2A_USE_CORE_CCSDS_TC_SPACE_DATA_LINK_PROTOCOL` オプションをそれぞれ `ON` に設定すること．
どの実装？セクション分かれてて意味が取りにくい。それぞれのセクションに書いたらいいのでは。

2024-04-08 09:23 UTC, sksat commented on docs/general/architecture.md
> +想定するアーキテクチャでは，通信機と接続され衛星の全体を司る MOBC (Main On-Board Computer) と，MOBC の配下に接続される sub OBC (AOCS OBC など) のそれぞれ向けの機能が存在する．
just もう書いてるのでわかる（無駄に長い） + 「それぞれの機能」is 何
```suggestion
通信機と接続され衛星の全体を司る MOBC (Main On-Board Computer) と，MOBC の配下に接続される sub OBC (AOCS OBC など) が存在する．
```

2024-04-09 15:08 UTC, meltingrabbit commented on docs/application/overview.md
> +`ON` にすることで，test app 以外の全ての [c2a-core Application](/applications/) をビルドする．
そこを消すのは読み取れなかった（「test app 以外」を足すレビューだと捉えれた），がOK．
直します．

2024-04-09 15:09 UTC, meltingrabbit commented on docs/application/overview.md
> +`ON` にすることで，test app 以外の全ての [c2a-core Application](/applications/) をビルドする．
では，合わせて  `C2A_USE_ALL_CORE_TEST_APPS` の方も消しますね．

2024-04-09 15:11 UTC, meltingrabbit commented on docs/core/ccsds.md
> +この実装をコンパイル対象に含める場合は，以下の `C2A_USE_CORE_CCSDS_AOS_SPACE_DATA_LINK_PROTOCOL`, `C2A_USE_CORE_CCSDS_TC_SPACE_DATA_LINK_PROTOCOL` オプションをそれぞれ `ON` に設定すること．
それぞれのセクション，というのはないが，指摘は理解するので，表現を変えました．

2024-04-09 15:13 UTC, meltingrabbit commented on docs/general/architecture.md
> +想定するアーキテクチャでは，通信機と接続され衛星の全体を司る MOBC (Main On-Board Computer) と，MOBC の配下に接続される sub OBC (AOCS OBC など) のそれぞれ向けの機能が存在する．
そのままとりこみました

2024-04-09 15:13 UTC, meltingrabbit commented
@sksat 指摘事項直しました

2024-04-11 05:23 UTC, sksat approved these changes

2024-04-11 05:23 UTC, meltingrabbit commented
マージしてリリースPR作ります

2024-04-11 05:24 UTC, merged

2024-04-11 05:26 UTC, sksat commented
@meltingrabbit CHANGELOG 書いて