WIP:
arkedge/c2a-core pull request #329
Opened 2024-04-03 08:36 UTC by meltingrabbit

## 概要
ひとことで

## Issue
- 関連する issue

## 詳細
詳しく

## 検証結果
test へのリンクや，検証結果へのリンク

## 影響範囲
XX系の動作がガラッと変わる，とか．

## 補足
何かあれば

2024-04-03 09:16 UTC, meltingrabbit commented on tlm_cmd/common_packet/space_packet/common_tlm_packet.c
> +#endif
@sksat 
build option `C2A_MOBC_FEATURES` の ON/OFF によって，こういう感じで処理を買えるつもりです．
この option をみて，
```
add_definitions("-DC2A_MOBC_FEATURES")
```
みたく入れようかと思うんですが，この define の名前どうするのが良いですか？

build option と合わせて `C2A_MOBC_FEATURES` がいいのか，それとも別がいいのか，など意見ください．（ `C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP` も同様 ）

2024-04-04 13:17 UTC, sksat requested changes

2024-04-04 13:17 UTC, sksat commented on CMakeLists.txt
> +endif()
`target_compile_definitions()` の target には `add_library()` もしくは `add_executable()` された target である必要があります。そして CMake あるあるの罠として意外とこのファイルは上から逐次実行されるので、この if ブロックを `add_library()` よりも後に書いてください。

2024-04-05 00:12 UTC, meltingrabbit commented on CMakeLists.txt
> +endif()
@sksat 修正しました．再度 review お願いします．

2024-04-08 04:53 UTC, sksat requested changes

2024-04-08 04:53 UTC, sksat commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
結局この option は生やさず、必ずユーザ定義させることとしたはず（PR description にもまだある）

2024-04-08 05:23 UTC, meltingrabbit commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@sksat すいません，消し忘れです．消しました

2024-04-08 05:27 UTC, sksat commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@meltingrabbit PR description にも、です

2024-04-08 05:29 UTC, meltingrabbit commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@sksat たしかに．
descriptionを書き直しました．

2024-04-08 05:41 UTC, sksat commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@meltingrabbit ついでに description もうひとつ。`src/src_user/settings/tlm_cmd/common_tlm_packet_define.c` の例があるのは examples/subobc だけじゃないでしょう。また、「独自に」という語の意味するところが不明瞭です。

c2a-core 開発者向け（つまり PR description）に適切なのは、
- 前提: CTP の Global Time はユーザ毎に定義できる
- 実装: この定義を行う `CTP_set_global_time()` を `src/src_user/settings/tlm_cmd/common_tlm_packet_define.c` に分割した
- 補足: MOBC や Sub OBC 特有の例が example user にあるならその説明

のような書き方ではないでしょうか。

2024-04-08 05:58 UTC, meltingrabbit commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@sksat 書き直しました．
この点はとくに mobc / subobc 独自の例はないので，mobc だけ例示しています．

2024-04-08 06:02 UTC, sksat commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@meltingrabbit feature で分岐するのが `CTP_set_on_board_subnet_time()` で、settings に分けたのが `CTP_set_global_time()` では。両方 `CTP_set_on_board_subnet_time()` になってます。

2024-04-08 06:03 UTC, meltingrabbit commented on examples/mobc/src/src_user/settings/tlm_cmd/common_tlm_packet_define.c
> +  // User 独自の値を設定する場合は， C2A_USE_DEFAULT_GLOBAL_TIME_IN_CTP を OFF にすること
@sksat すまん直した

2024-04-08 06:04 UTC, sksat approved these changes

2024-04-08 06:15 UTC, merged