Move NodeJS package manager to pnpm
arkedge/c2a-core pull request #353
Opened 2024-05-17 07:12 UTC by sksat

## 概要
SSIA

## Issue
- #280  

## 詳細
- https://github.com/arkedge/c2a-core/issues/280#issuecomment-1895115779
- pnpm の方がまともで速く、AE 全体で pnpm に寄せることにしたため

## 検証結果
test へのリンクや，検証結果へのリンク

## 影響範囲
C2A Boom

2024-05-17 07:15 UTC, KOBA789 requested changes

2024-05-17 07:15 UTC, KOBA789 commented on docs/sils/c2a_dev_runtime.md
> +pnpm install
pnpm は Node.js にバンドルされていないので corepack で連れてくる必要がある。
あと、corepack で連れてくるために package.json に pnpm のバージョン情報を書く必要がある。
```suggestion
corepack enable
pnpm install
```

2024-05-17 07:26 UTC, sksat commented on docs/sils/c2a_dev_runtime.md
> +pnpm install
`actions/setup-node` でも `corepack enable` する必要あるのかな（パッと見やらずに使えそうなドキュメントになってるが）

2024-05-17 07:40 UTC, KOBA789 commented on docs/sils/c2a_dev_runtime.md
> +pnpm install
`actions/setup-node` の場合は不要そう

2024-05-17 07:44 UTC, sksat commented on docs/sils/c2a_dev_runtime.md
> +pnpm install
でも今落ちてるんだよね

2024-05-17 08:07 UTC, KOBA789 commented on docs/sils/c2a_dev_runtime.md
> +pnpm install
エーッ　じゃあ必要なのかもしれんね……（pnpm サポートはキャッシュ制御だけで、pre-installed ということではないのか？）

2024-05-17 09:08 UTC, sksat commented on docs/sils/c2a_dev_runtime.md
> +pnpm install
そういうことな気はしつつ、だったらドキュメントに書いてある workflow 間違ってね？という感（まあ手癖で書いたのかな......）

2024-07-04 07:51 UTC, sksat commented
rebase

2024-07-08 13:35 UTC, KOBA789 commented
```
! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.4.0.tgz
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

とのことですけども……（初めて見るエラーだ）

2024-07-08 13:36 UTC, KOBA789 commented
あーこれ既に actions/setup-node が pnpm 入れてるから pnpm のインストールが衝突してるのか？

2024-07-16 16:08 UTC, sksat commented
rebase

2024-07-16 16:11 UTC, sksat commented
いや、`actions/setup-node` なくても出るな

2024-07-22 19:12 UTC, sksat commented
やや不本意だが `pnpm/action-setup` 使うか

2024-07-22 19:48 UTC, KOBA789 approved these changes
そういえば、`pnpm` が打ちづらいのは公式も認識しているようで、インストール手順の最後にエイリアスを貼る方法が紹介されているほどです。
もしかしたら C2A のドキュメントでもそれを案内してもいい、かもしれない（要らんことは案内しないほうがいいという説もかなりあるけど）
https://pnpm.io/installation#using-a-shorter-alias

2024-07-22 19:50 UTC, sksat commented
要らんことは案内しない方がいい（分かっている人は調べりゃ勝手にやるし、分かってない人が alias をゴチャッとやると悲惨だしデバッグが困難になる）

2024-07-22 19:51 UTC, sksat commented
そもそも打つ頻度がそんなにだし

2024-07-22 19:54 UTC, merged